name: Release working and versioned builds for Foundry VTT

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  working-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Compiles source code into the essential Foundry VTT release files
        run: |
          rm -rf dist
          mkdir dist
          # Ensure system.json is inside dist for release
          cp src/system.json build/system.json
          cp src/system.json dist/system.json
          # Ensure template.json is inside the system.zip source
          cp src/template.json build/template.json
          # Ensure non TS and SCSS files inside the build
          cp -vr src/assets build/assets
          cp -vr src/lang build/lang
          mv build/system.css build/styles/system.css
          cp -vr src/templates build/templates
          cd build
          zip -vr dist/system.zip . -x ".DS_Store"

      - name: Update compiled working assets into the v0.0.0 release
        run: |
          version="v0.0.0"
          manifest_url="https://github.com/callunaborealis/fvtt-mutants-and-masterminds-3e/releases/$version/download/system.json"
          gh release upload $version dist/system.json dist/system.zip --clobber

  versioned-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Compiles source code into the essential Foundry VTT release files
        run: |
          rm -rf dist
          mkdir dist
          # Ensure system.json is inside dist for release
          cp src/system.json build/system.json
          cp src/system.json dist/system.json
          # Ensure template.json is inside the system.zip source
          cp src/template.json build/template.json
          # Ensure non TS and SCSS files inside the build
          cp -vr src/assets build/assets
          cp -vr src/lang build/lang
          mv build/system.css build/styles/system.css
          cp -vr src/templates build/templates
          cd build
          zip -vr dist/system.zip . -x ".DS_Store"

      - name: Upload compiled assets as a versioned release
        run: |
          # refs/tags/v**.**.** -> v**.**.**
          version=${GITHUB_REF##*/}
          manifest_url="https://github.com/callunaborealis/fvtt-mutants-and-masterminds-3e/releases/$version/download/system.json"
          gh release create $version dist/system.json dist/system.zip --notes "Link to manifest URL: $manifest_url"
