name: Release working and versioned builds for Foundry VTT

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  working-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: pnpm install

      - name: Compiles source code into the essential Foundry VTT release files
        run: |
          rm -rf dist && mkdir dist
          pnpm run build
          version="v0.0.0"
          manifest_url="https://github.com/callunaborealis/fvtt-mutants-and-masterminds-3e/releases/$version/download/system.json"
          gh release upload $version ../dist/system.json ../dist/system.zip --clobber

  versioned-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: pnpm install

      - name: Compiles source code into the essential Foundry VTT release files
        run: |
          rm -rf dist && mkdir dist
          pnpm run build
          # refs/tags/v**.**.** -> v**.**.**
          version=${GITHUB_REF##*/}
          manifest_url="https://github.com/callunaborealis/fvtt-mutants-and-masterminds-3e/releases/$version/download/system.json"
          gh release create $version ../dist/system.json ../dist/system.zip --notes "Link to manifest URL: $manifest_url"
